### ISSUE TITLE
[Request] Sync streams from Twitch

### ISSUE THREAD

**Issue by Hund** [RadicalEd360/streamlink-curses#2]
The Twitch CLI-client [twitchy](https://github.com/BasioMeusPuga/twitchy) allows you to sync all the streams from a user with the command `twitchy -s <username>`. It would be nice if this was possible with streamlink-curses as well. :)

**Comment by RadicalEd360** [comment]
i will look into this :)

**Comment by Hund** [comment]
Cool, thanks! :)

 It should be noted that twitchy only allows for one-way sync. Which is good enough, but it would be cool woth two-way sync as well. I don't know how much work it would be to add support for that though. But the syntax should none the less be something like:

```
livestreamer-curses -s/--sync <service> -u/--user <username>
```

Since Streamlink supports more services than just Twitch, it would be logic to have to specify the service as well. :)

**Comment by RadicalEd360** [comment]
this is a good idea :)

**Comment by RadicalEd360** [comment]
i am rewriting the entire program, this will be a feature, 1 way sync will be at first, then eventually 2 way sync, 2 way sync will require oauth token

**Comment by Hund** [comment]
That sounds great! :)

**Comment by RadicalEd360** [comment]
new project is up, 1 way sync supported, ive renamed it to streamcurse

**Comment by RadicalEd360** [comment]
i will be adding 2 way sync support in a later update, along with irc support for connecting to the chatroom of streamer, both of which require oauth support, so look forward to that :)
i am closing this issue for now

**Comment by Hund** [comment]
Cool, thansks! I found one issue  though, the config is placed in `$HOME`, it should always be in `$CONFIG`. And since it has it's own folder, there's no need to name the config `streamlink-cursesrc`, it should be fine with like `config`. :)

Also, `j` is up and `k` is down and the colors in the settings doesn't work, it totallt ignore them.

**Comment by RadicalEd360** [comment]
its no longer using streamlink-cursesrc, the old streamlink-cursesrc will be incompatible with the new config.ini file, the new format is alot cleaner and safer, the old one was just a python script itself, which would execute any code written in it

the config color scheme requires both a foreground and a background in the format
`option = foreground background`
atm i havent implemented html color codes but will in the future, you can use the terminals color code instead of color name tho, use colortest.py to show your terminals available colors and how they will look

i have now switched j/k to match vims j/k thx for the catch :smile: 

originally it was using ~/.streamcurse as program storage folder, but i agree it should be placed in ~/.config or wherever the user wants to help clean up the home folder, so i have updated it to store all data except cache within these directories:
$XDG_CONFIG_HOME/streamcurse
$CONFIG/streamcurse
$HOME/.config/streamcurse
whichever set env var it finds first will be used
cache is stored in /tmp/
